name: Wind_Change
version: '1.0-SNAPSHOT'
main: enxada.TesteRecrutamento.Wind_Change
api-version: '1.21'
authors: [ PauloHolanda ]
description: Um plugin spigot que modifica o Wind Charge.
commands:
  windcharger:
    description: Comando para configurar o Wind Charge
    usage: /windcharge or /windcharge config <value>